version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bookings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookings
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - booking-net

  frontend:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - booking-net

volumes:
  db-data:

networks:
  booking-net:
